
### 查询
GET http://localhost:22222/article?catalogId=1 HTTP/1.1


### 增加
POST http://localhost:22222/article/ HTTP/1.1
content-type:application/json

{"encontent":"","mixcontent":"[]","chcontent":"","catalogid":}

### 修改
PUT http://localhost:22222/article/ HTTP/1.1
content-type:application/json

{"id":1,"encontent":"hello"}
    
    
