### 测试路由
GET http://localhost:22222/juejin/test HTTP/1.1

### 获取用户列表
GET http://localhost:22222/juejin/articles HTTP/1.1

### 点赞
POST http://localhost:22222/juejin/star HTTP/1.1
content-type:application/json

{"id":"7042157518625177608"}


### 签到
GET http://localhost:22222/juejin/qiandao HTTP/1.1