
### 查询
GET http://localhost:22222/trader HTTP/1.1



### 增加
POST http://localhost:22222/trader/ HTTP/1.1
content-type:application/json

{"name":"测试","parterid":"10059","key":"8EBCBFD869EC825F7FDCE95E6902BA65","status":1,"addTime":"2023-12-08 06:54:00"}

### 修改
PUT http://localhost:22222/trader/ HTTP/1.1
content-type:application/json

{"id":5}
    
### 计算余额
POST http://localhost:22222/trader/balance HTTP/1.1
