### 查询
GET http://localhost:22222/util/bdy/video/xxx

### see
GET http://localhost:22222/util/see?key=怪奇物语

### 解析海词词典
GET http://localhost:22222/util/translate?word=bid

### 获取基金信息
GET http://localhost:22222/util/invest

### 解析blibli
GET http://localhost:22222/util/bb-test?link=https://www.bilibili.com/video/BV1oT411h7ZL

### 查询本周工作时长
GET http://10.4.6.175:22222/util/checking-in?name=huangyangteng&pass=1234

### 取消关注
GET http://10.4.6.175:22222/util/cancel-attention?ids=25476670,26124833,7106249,119115330,18534696,90614797,15049092,17171565,104352019,95209550,344849038,176321970,298289539,27038754,92803415,294666436,112836656

### 周报生成
POST http://localhost:22222/util/reporter
content-type:application/json

{
    "title": "2018年8月第5周工作周报",
    "person": "张三",
    "date": [
        "2018年8月27日",
        "2018年8月31日"
    ],
    "thisWeek": [
        {
            "name": "移动视频彩铃",
            "progress": "80",
            "deadline": "3.31",
            "content": [
                "转盘活动问题，定位抽奖功能异常原因：获取用户信息数据延迟，添加延迟处理，解决了异常。",
                "转盘活动测试，对领导提出的意见进行系统测试和优化。",
                "配合新版本H5改造：添加新接口，以满足H5需求"
            ]
        },
        {
            "name": "联通视频彩铃",
            "progress": "80",
            "deadline": "3.31",
            "content": [
                "转盘活动问题，定位抽奖功能异常原因：获取用户信息数据延迟，添加延迟处理，解决了异常。",
                "转盘活动测试，对领导提出的意见进行系统测试和优化。",
                "配合新版本H5改造：添加新接口，以满足H5需求"
            ]
        }
    ],
    "nextWeek": [
        {
            "name": "视频制作",
            "progress": "80",
            "deadline": "",
            "content": [
                "完成IVVRr任务的获取及渲染",
                "完成形状功能的渲染"
            ]
        }
    ]
}