### 查询
GET http://localhost:22222/util/bdy/video/xxx

### see
GET http://localhost:22222/util/see?key=怪奇物语

### 解析海词词典
GET http://localhost:22222/util/translate?word=bid

### 获取基金信息
GET http://localhost:22222/util/invest

### 解析blibli
GET http://localhost:22222/util/bb-test?link=https://www.bilibili.com/video/BV1oT411h7ZL
