

### 解析blibli视频
POST http://localhost:22222/watch/bb HTTP/1.1
content-type:application/json

{"link":"https://www.bilibili.com/video/BV1Mg411g7C8?p=2","onlySrc":0}

### 解析acfun视频
POST http://localhost:22222/watch/acfun HTTP/1.1
content-type:application/json

{"link":"https://www.acfun.cn/v/ac31616020","onlySrc":0}


### 添加bb视频
POST http://localhost:22222/watch/add HTTP/1.1
content-type:application/json

{"link":"https://www.bilibili.com/video/BV1Mg411g7C8","type":"letter"}


### 添加acfun视频
POST http://localhost:22222/watch/add HTTP/1.1
content-type:application/json

{"link":"https://www.acfun.cn/v/ac31616020","type":"gradute","from":"acfun"}

### 删除视频
POST http://localhost:22222/watch/delete HTTP/1.1
content-type:application/json

{"ids":[10,11]}



### 获取bb视频
GET http://localhost:22222/watch/bb-list HTTP/1.1