name: GERT SERVER

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest # 第三方的 action
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}

          # 由于网络情况，很容易超时，设置为60s
          connect_timeout: 60s

          # 将工作目录下的文件全部拷贝到部署服务器的工作目录
          scp: |
            ./* => /root/geek-server
            # 完成拷贝后在部署服务器执行的命令：进入项目目录，安装生产依赖，并使用 pm2 管理
          last_ssh: |
            echo "run geek-server" 
            sh /root/geek-server/deploy-github.sh
  
